apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-url
data:
  PRODUCT_SERVICE_URL: 'http://product.default.svc:8080'
  USER_SERVICE_URL: 'http://user.default.svc:8080'
  RATING_SERVICE_URL: 'http://rating.default.svc:8080'
  ORDER_SERVICE_URL: 'http://order.default.svc:8080'  

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-db
data:
  MONGO_HOST: 'cart-db.default.svc:27017'
