apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
spec:
  selector:
    matchLabels:
      app: cart
  replicas: 1
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart-container
        image: tmdwn0704/all-in-one-cart:1.0
        command: ["/bin/sh", "-c"]
        args:
        - ./wait-for-it.sh cart-db.default.svc:27017 -t 0;
          node app.js;
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: cart-url
        - configMapRef:
            name: cart-db

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 5

        readinessProbe:
          httpGet:
            path: /health
            port: 8080 
          initialDelaySeconds: 0
          periodSeconds: 2

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-db
  template:
    metadata:
      labels:
        app: cart-db
    spec:
      containers:
      - image: mongo
        name: mongo-container
        ports:
        - containerPort: 27017
          name: mysql
        volumeMounts:
        - name: cart-volume
          mountPath: /data/db
      volumes:
      - name: cart-volume
        emptyDir: {}
        ## TODO: storage class
        # persistentVolumeClaim:
        #   claimName:  cart-pvc
