apiVersion: v1
kind: Service
metadata:
  name:  cart
spec:
  selector:
    app: cart
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: cart-db
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: cart-db
